### ISSUE TITLE
AmbientLightManager

### ISSUE THREAD

**Issue by sanke-t** [mitoyarzun/zxingfragmentlib#23]
The torch won't turn on by itself. Are the onKeyDown() and onKeyup() overriding the functions of AmbientLightManager?
Please help.

**Comment by mitoyarzun** [comment]
Hi, sorry for the delay.

Since we are not using the PreferencesActivity, you should set the auto torch "manually". The code to do this is the following:

``` java
SharedPreferences.Editor editor = PreferenceManager.getDefaultSharedPreferences(this).edit();
editor.putString(PreferencesActivity.KEY_FRONT_LIGHT_MODE, FrontLightMode.AUTO.toString());
editor.commit();
```

Please let me know if it works.

**Comment by sanke-t** [comment]
Thanks a ton man, this works.

**Comment by mitoyarzun** [comment]
Great!
