### ISSUE TITLE
Application goes blank for couple of seconds then resumes to normal when the camera is initiated

### ISSUE THREAD

**Issue by kfikani** [mitoyarzun/zxingfragmentlib#24]
I have successfully added the library to my project and it works as expected. One thing that I'm facing is that when I initiate the barcode scanner, the whole application goes blank for couple of seconds and then the camera shows up. The following times, when the camera is initiated the application doesn't go blank. Have anyone faced a similar issue? If yes what was your solution? Thanks!

**Comment by mitoyarzun** [comment]
I haven't noticed this, what is your device and Android version?

**Comment by rhavran** [comment]
@karim-atheerlabs Try to put <SurfaceView    android:layout_width="0px"  android:layout_height="0px" /> into your activity layout, then fragment should works fine.

**Comment by kfikani** [comment]
Thanks for the reply. Well it seems that it does that prior to Android 5.0. Not an issue anymore.
