### ISSUE TITLE
advanced history handling

### ISSUE THREAD

**Issue by Helle007** [mitoyarzun/zxingfragmentlib#25]
Hi, a real nice feature would be an advanced history handling.
After a barcode is scanned, it would be great to have a notification, if the new scanned barcode is a new one or it already exist in the history. A display on the screen or a sound would be possible options.

thanks,

**Comment by mitoyarzun** [comment]
Hi!
This would be nice but falls beyond the scope of this library, it could be implemented in the app level.

If the data needs to be persistent I would suggest using a simple sqlite database, and if it doesn't need to be stored after closing the app a Set<String> should be enough.
